version: "3.8"
services:
  
  reverse-proxy:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - host-network
      - internal-network
    depends_on:
      - webapp
  
  webapp:
    container_name: webapp
    build:
      context: webapp
      dockerfile: DemoWebApp/Dockerfile
    networks:
      - internal-network
    depends_on:
      - mongo
      - redis
      
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes: 
      - mongodata:/data/db
    networks:
      - internal-network
        
  redis:
    container_name: redis
    image: redis:latest
    volumes: 
      - redisdata:/data
    networks:
      - internal-network
    
volumes:
    mongodata:
    redisdata:

networks:
  host-network:
    external: true
  internal-network:
    external: false