version: "3.8"
services:
  
  webapp:
    build:
      context: ./webapp/DemoWebApp
      dockerfile: Dockerfile
    networks:
      - host-network
      - internal-network
    depends_on:
      - mongo
      - redis
  
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes: 
      - mongodata:/data/db
    networks:
      - internal-network
        
  redis:
    container_name: redis
    image: redis:latest
    volumes: 
      - redisdata:/data
    networks:
      - internal-network
    
volumes:
    mongodata:
    redisdata:

networks:
  host-network:
    external: true
  internal-network:
    external: false